name: Tests

on:
  push:
    branches:
      - main

# push:
#   branches:
#     - main

jobs:
  tests:
    name: Ryn test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Copy .env file
        run: |
          cp .env.ci .env

      - name: Run Composer
        run: |
          composer install --no-interaction
          composer update


      - name: Run test suite
        run: |
          php artisan key:generate
          php artisan test
