name: Tests

on:
  push:
    branches:
      - main

# push:
#   branches:
#     - main

jobs:
  tests:
    name: Ryn test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MY_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 20s 
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Copy .env file
        run: |
          cp .env.ci .env

      - name: Run Composer
        run: |
          composer install --no-interaction
          composer update

      - name: Env_file
        run: cp .env.example .env

      - name: Run test suite
        env:
          DB_DATABASE: laravel
        run: |
          php artisan key:generate
         
          npm i
          npm run build
          php artisan test
